apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: 2019-03-19T12:11:24Z
  generation: 20
  labels:
    run: colorapi
  name: colorapi
  namespace: default
  resourceVersion: "28041489"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/colorapi
  uid: 1db26cce-4a40-11e9-bc4f-0a58ac1f01ad
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: colorapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: colorapi
    spec:
      containers:
      - image: markharrison/colorapi:v1
        imagePullPolicy: IfNotPresent
        name: colorapi
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-13T09:49:26Z
    lastUpdateTime: 2019-05-13T09:49:26Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-19T12:11:24Z
    lastUpdateTime: 2019-05-13T09:54:41Z
    message: ReplicaSet "colorapi-cbf44f9bc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 20
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
